[build]
  command = "npm run build"
  publish = ".next"

[dev]
  command = "npm run dev"
  port = 3000

[build.environment]
  NODE_VERSION = "18"

[context.production.environment]
  NEXT_PUBLIC_API_URL = "https://veteralia-backend.herokuapp.com"
