[build]
  base = "frontend"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

[context.production.environment]
  NEXT_PUBLIC_API_URL = "https://veteralia-backend.herokuapp.com"
