// Spanish veterinary specialties
export const VET_SPECIALTIES_ES = [
  'Anestesia y analgesia',
  'Bienestar animal',
  'Medicina del comportamiento',
  'Farmacología clínica',
  'Odontología',
  'Dermatología',
  'Emergencias y cuidados críticos',
  'Medicina interna - Cardiología',
  'Medicina interna - Grandes animales',
  'Medicina interna - Neurología',
  'Medicina interna - Oncología',
  'Medicina interna - Pequeños animales',
  'Medicina de animales de laboratorio',
  'Microbiología',
  'Nutrición',
  'Oftalmología',
  'Patología',
  'Medicina avícola',
  'Medicina preventiva',
  'Radiología',
  'Práctica aviar',
  'Práctica en ganado de carne',
  'Práctica en caninos y felinos',
  'Práctica lechera',
  'Práctica equina',
  'Práctica de mamíferos exóticos',
  'Práctica felina',
  'Práctica de animales de producción',
  'Práctica de reptiles y anfibios',
  'Práctica en medicina de refugio',
  'Gestión sanitaria porcina',
  'Medicina deportiva y rehabilitación',
  'Cirugía',
  'Teriogenología (Reproducción)',
  'Toxicología',
  'Medicina zoológica',
];
