// English veterinary specialties
export const VET_SPECIALTIES_EN = [
  'Anesthesia and Analgesia',
  'Animal Welfare',
  'Behavioral Medicine',
  'Clinical Pharmacology',
  'Dentistry',
  'Dermatology',
  'Emergency and Critical Care',
  'Internal Medicine - Cardiology',
  'Internal Medicine - Large Animal',
  'Internal Medicine - Neurology',
  'Internal Medicine - Oncology',
  'Internal Medicine - Small Animal',
  'Laboratory Animal Medicine',
  'Microbiology',
  'Nutrition',
  'Ophthalmology',
  'Pathology',
  'Poultry Veterinary Medicine',
  'Preventive Medicine',
  'Radiology',
  'Avian Practice',
  'Beef Cattle Practice',
  'Canine and Feline Practice',
  'Dairy Practice',
  'Equine Practice',
  'Exotic Companion Mammal Practice',
  'Feline Practice',
  'Food Animal Practice',
  'Reptile and Amphibian Practice',
  'Shelter Medicine Practice',
  'Swine Health Management',
  'Sports Medicine and Rehabilitation',
  'Surgery',
  'Theriogenology (Reproduction)',
  'Toxicology',
  'Zoological Medicine',
];
